<a href="https://colab.research.google.com/github/airprakriti/test-repo/blob/main/MLassignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Q-1 a)

In [ ]:
import numpy as n
arr=[1,2,3,4,5,6,7]
reverse_arr=arr[::-1]
print(reverse_arr)

[7, 6, 5, 4, 3, 2, 1]


In [ ]:
import numpy as n
arr=[1,2,3,4,5,6,7]
reverse_arr=n.flip(arr)
print(reverse_arr)

[7 6 5 4 3 2 1]


Q-1 b)

In [ ]:
import numpy as n
arr=[[1,2,3],[4,5,6]]
flat=n.array([i for sublist in arr for i in sublist])
print(flat)

[1 2 3 4 5 6]


In [ ]:
import numpy as n
arr=[[1,2,3],[4,5,6]]
flatten_arr=n.ravel(arr)
print(flatten_arr)

[1 2 3 4 5 6]


Q-1 c)

In [ ]:
import numpy as n
arr1=[[1,2,3],[4,5,6]]
arr2=[[1,2,3],[4,5,6]]
if (n.array_equal(arr1,arr2)):
 print("equal")
else:
  print("unequal")

unequal


Q-1 d) **DOUBT**

In [ ]:
import numpy as np

# Given array
x = np.array([4,6,6,9,0,6,9,5,6])

# Finding the most frequent value using numpy
unique,counts = np.unique(x, return_counts=True)
most_common_value = unique[np.argmax(counts)]

# Finding the indices of the most frequent value
indices = np.where(x == most_common_value)[0]

print("Most frequent value:", most_common_value)
print("Indices of the most frequent value:", indices)


Most frequent value: 6
Indices of the most frequent value: [1 2 5 8]


Q-1 e)

In [ ]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = np.sum(gfg)
print(total_sum)


45


In [ ]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
row_wise_sum = np.sum(gfg, axis=1)
print(row_wise_sum)



[[14]
 [16]
 [15]]


In [ ]:
import numpy as n

gfg = n.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
column_wise_sum = n.sum(gfg, axis=0)
column_wise_sum


matrix([[20,  9, 16]])

Q-1 f)

In [ ]:
import numpy as np
#n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
diagonal_sum = np.sum(np.diagonal(gfg))
diagonal_sum

13

In [ ]:
import numpy as np
#sum of the eigenvalues of a matrix is equal to the trace of the matrix
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
eigenvalues = np.linalg.eigvals(n_array)#This line computes the eigenvalues of the matrix n_array using the eigvals function from the numpy.linalg module. The eigenvalues are stored in the variable eigenvalues.
sum_eigen= np.sum(eigenvalues)
print(sum_eigen)


176.0000000000001


In [ ]:
import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
eigenvalues, eigenvectors = np.linalg.eig(n_array)

# Sum of all elements of the eigenvectors matrix
sum_eigenvectors = np.sum(eigenvectors)
print(sum_eigenvectors)


2.0208354705104603


In [ ]:
import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
inverse_matrix = np.linalg.inv(n_array)
print(inverse_matrix)


[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
determinant = np.linalg.det(n_array)
print(determinant)


137180.0000000001


Q-1 g)

In [ ]:
import numpy as np

# Define the matrices
#p = np.array([[1, 2], [2, 3]])
#q = np.array([[4, 5], [6, 7]])
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])


# Matrix multiplication
result_mult = np.dot(p, q)

# Flatten the matrices and stack them
p_flat = p.flatten()
q_flat = q.flatten()
data = np.stack((p_flat, q_flat), axis=0)

# Calculate covariance matrix
cov_matrix = np.cov(data)

print("Matrix Multiplication Result:")
print(result_mult)

print("\nCovariance Matrix:")
print(cov_matrix)


Matrix Multiplication Result:
[[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance Matrix:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


Q-1 h)

In [ ]:
#INNER PRODUCT
import numpy as np

# Define the matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Calculate the Frobenius inner product
inner_product = np.sum(x * y)

# Print the result
print("Frobenius inner product:", inner_product)


Frobenius inner product: 79


In [ ]:
#OUTER PRODUCT
import numpy as np

# Define the matrices
x = np.array([[1, 2], [3, 4]])
y = np.array([[0, 5], [6, 7]])

# Flatten the matrices to treat them as vectors
x_flat = x.flatten()
y_flat = y.flatten()

# Calculate the outer product
outer_product = np.outer(x_flat, y_flat)

# Print the result
print("Outer product:\n", outer_product)


Outer product:
 [[ 0  5  6  7]
 [ 0 10 12 14]
 [ 0 15 18 21]
 [ 0 20 24 28]]


In [ ]:
import numpy as np

# Define the matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Calculate the Cartesian product using meshgrid
X, Y = np.meshgrid(x, y)

# Combine the matrices into a 3D array representing the Cartesian product
cartesian_product = np.stack((X, Y), axis=-1)

# Print the resulting Cartesian product
print(cartesian_product)


[[[ 2  1]
  [ 3  1]
  [ 4  1]
  [ 3  1]
  [ 2  1]
  [ 9  1]]

 [[ 2  5]
  [ 3  5]
  [ 4  5]
  [ 3  5]
  [ 2  5]
  [ 9  5]]

 [[ 2  0]
  [ 3  0]
  [ 4  0]
  [ 3  0]
  [ 2  0]
  [ 9  0]]

 [[ 2  5]
  [ 3  5]
  [ 4  5]
  [ 3  5]
  [ 2  5]
  [ 9  5]]

 [[ 2 10]
  [ 3 10]
  [ 4 10]
  [ 3 10]
  [ 2 10]
  [ 9 10]]

 [[ 2  3]
  [ 3  3]
  [ 4  3]
  [ 3  3]
  [ 2  3]
  [ 9  3]]]


Q-2 (a)

In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

absolute_values = np.abs(array)

print(absolute_values)


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

flattened_array = array.flatten()

percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])
print("Percentiles for flattened array:", percentiles_flattened)

percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles for each column:\n", percentiles_columns)

percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles for each row:\n", percentiles_rows)


Percentiles for flattened array: [-3.5 -0.5  2.5]
Percentiles for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

# Flatten the array
flattened_array = array.flatten()

# Mean, median, and standard deviation for flattened array
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

# Mean, median, and standard deviation for each column
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)

# Mean, median, and standard deviation for each row
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("Flattened array:")
print("Mean:", mean_flattened)
print("Median:", median_flattened)
print("Standard Deviation:", std_flattened)

print("\nColumns:")
print("Mean:", mean_columns)
print("Median:", median_columns)
print("Standard Deviation:", std_columns)

print("\nRows:")
print("Mean:", mean_rows)
print("Median:", median_rows)
print("Standard Deviation:", std_rows)


Flattened array:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Columns:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Rows:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


Q-2 (b)

In [ ]:
import numpy as np

a =[-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0]

# Floor
floor_values = np.floor(a)

# Ceiling
ceil_values = np.ceil(a)

# Truncated values
trunc_values = np.trunc(a)

# Rounded values
round_values = np.round(a)

print("Floor values:", floor_values)
print("Ceiling values:", ceil_values)
print("Truncated values:", trunc_values)
print("Rounded values:", round_values)


Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


Q-3 (a)

In [ ]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
#Get the indices of the 4 smallest elements
smallest_indices = np.argsort(array)[:4]
# Get the actual 4 smallest elements
smallest_elements = array[smallest_indices]



print(sorted_array)
print(sorted_indices)
print(smallest_elements)


[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]


In [ ]:
#SMALLEST 4 ELEMENTS
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)[:4]
print(sorted_array)



[10 16 16 52]


In [ ]:
#LARGEST 5 ELEMENTS
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

# Sort the array in descending order
sorted_array = np.sort(array)[::-1]

# Get the 5 largest elements
largest_elements = sorted_array[:5]

print(largest_elements)


[453  62  54  52  16]


In [ ]:
Q-3 (b)

In [ ]:
import numpy as np
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[array == array.astype(int)]
print(integer_elements)
float_elements = array[array != array.astype(int)]
print(float_elements)


[1. 2. 3. 2.]
[1.2 2.2]


Q-4

In [ ]:
import numpy as np
from PIL import Image

def img_to_array(path):
  """
  Reads an image from a specified path and saves it as a text file.

  Args:
    path: The path to the image file.

  Returns:
    None
  """

  # Load the image using PIL
  img = Image.open(path)

  # Convert the image to a NumPy array
  img_array = np.array(img)

  # Get the file name without extension
  file_name = path.split('/')[-1].split('.')[0]

  # Save the array as a text file
  np.savetxt(f"{file_name}.txt", img_array, fmt="%d")

# Example usage
img_path = "C:\Users\AKUL\OneDrive\Pictures\taeri\images (2).jpg"
img_to_array(img_path)


SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-17-472355a37d24>, line 28)